### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by gachiemchiep** [dougsm/egad#3]
Hello @dougsm 
Thank you for your great work. 

In December 2020, when I tried to build the *egad.sif* image, I had the following error

```bash
$  sudo singularity build egad.sif singularity.de

Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from mayavi) (1.16.5)
Collecting pyface>=6.1.1
  Downloading pyface-7.2.0.tar.gz (6.1 MB)
     |################################| 6.1 MB 62 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-opEUXH/pyface/setup.py'"'"'; __file__='"'"'/tmp/pip-install-opEUXH/pyface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-EoKnn5
         cwd: /tmp/pip-install-opEUXH/pyface/
    Complete output (7 lines):
    Reading version file /tmp/pip-install-opEUXH/pyface/pyface/_version.py
    Package version from version file: ('7.2.0', 'Unknown')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-opEUXH/pyface/setup.py", line 298, in <module>
        with open("README.rst", "r", encoding="utf-8") as readme:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
FATAL:   While performing build: while running engine: exit status 1
```

Since the service is executed by python3, I change from pip2 to pip3 and use python3 to compile dependencies of dexnet.  The image is built successfully.

```bash
%apprun datasetgen
    cd /home/co/egad/scripts
    xvfb-run python3 generate_dataset.py ${@}
```

Unfortunately, the following error happens when I tried to create a new dataset

```bash
$ singularity run -B /datadrive/datasets/grasping/egad/test:/output  --app datasetgen egad.sif

Mesh: 0000_0098, Diversity: 0.00
Re-ranking Mesh Pool
Traceback (most recent call last):
  File "generate_dataset.py", line 587, in <module>
    run()
  File "generate_dataset.py", line 583, in run
    DiversityExperiment(args).run()
  File "generate_dataset.py", line 546, in run
    self.neat.run(2000, self.evaluate_genomes)
  File "/home/co/egad/egad/cppn_neat.py", line 218, in run
    winner = self._pop.run(fitness_function, generations)
  File "/usr/local/lib/python3.6/dist-packages/neat/population.py", line 89, in run
    fitness_function(list(iteritems(self.population)), self.config)
  File "generate_dataset.py", line 518, in evaluate_genomes
    print('Max Diversity Pool: {:0.2f}'.format(all_flat[0]))
IndexError: list index out of range
```

Would you mind take a look at this.? 
Thank you

**Comment by dougsm** [comment]
Hey @gachiemchiep,
This is an unfortuante side effect of the DexNet repo being only python 2 compatible, so with python2 end of life some of the dependencies might be broken.  As you've found, it doesn't run with python 3 due to lots of incompatible code.

For your specific error, pyface 7 is no longer python 2 comatible.  I think the solution here would be to change the dependency to be `pyface==6.1.2` which is the last version compatible with python 2.  Hopefully that helps.

**Comment by gachiemchiep** [comment]
@dougsm Thanks. I made some changes so the singularity can be built successfully now. 

https://github.com/dougsm/egad/pull/5
